# Generated by Django 4.0.4 on 2022-07-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='create_user',
        ),
    ]
